/**:
  ros__parameters:
    tensorrt:
      onnx_path: $(var data_path)/mask2former_r50_8xb2-90k_cityscapes-static-512x1024.onnx
      precision: fp32
    detector_config:
      mean: [123.675, 116.28, 103.53]
      std: [58.395, 57.12, 57.375]
