/**:
  ros__parameters:
    tensorrt:
      onnx_path: $(var directory/onnx)/rtmdet_x_8xb32-300e_coco-static-640x640.onnx
      precision: fp32
    detector:
      mean: [123.675, 116.28, 103.53]
      std: [58.395, 57.12, 57.375]
      box_format: XYXYS
      score_threshold: 0.2
