/**:
  ros__parameters:
    tensorrt:
      onnx_path: $(var directory/onnx)/rfdetr-base-static_560x560.onnx
      precision: fp32
    detector:
      mean: [124.16, 116.77, 103.94]
      std: [58.624, 57.344, 57.6]
      box_format: XYWH_NORM
      score_threshold: 0.5
